<a href="https://colab.research.google.com/github/Faizaa01/Deep_Learning_Practices/blob/main/PyTorch_nnModule_Torch_optim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

Ver 1

In [ ]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [ ]:
features = torch.rand(10,5)

In [ ]:
model = Model(features.shape[1])
# model.forward(features)
model(features)

tensor([[0.6103],
        [0.6697],
        [0.6600],
        [0.5958],
        [0.6086],
        [0.6062],
        [0.6304],
        [0.6654],
        [0.6190],
        [0.6652]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.1129,  0.2341, -0.0498, -0.0199,  0.1539]], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Ver 2

In [ ]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)

    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
model = Model(features.shape[1])
model(features)

tensor([[0.5404],
        [0.5404],
        [0.5404],
        [0.5433],
        [0.5244],
        [0.5404],
        [0.5404],
        [0.5404],
        [0.5404],
        [0.5404]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[-0.1225, -0.4350,  0.3184,  0.3666,  0.0972],
        [-0.0270,  0.0743, -0.1467,  0.3251, -0.0366],
        [ 0.0781, -0.4246, -0.0461, -0.2138, -0.3591]], requires_grad=True)

In [ ]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Ver 3

In [ ]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3, 1),
      nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [ ]:
model = Model(features.shape[1])
model(features)

tensor([[0.5646],
        [0.5704],
        [0.5666],
        [0.5683],
        [0.5645],
        [0.5623],
        [0.5685],
        [0.5703],
        [0.5626],
        [0.5680]], grad_fn=<SigmoidBackward0>)

In [ ]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
model.network[0].weight, model.network[2].weight

(Parameter containing:
 tensor([[-0.2593, -0.1388,  0.1155,  0.0464,  0.1250],
         [-0.2227,  0.2588,  0.1909,  0.2202,  0.1358],
         [ 0.0154,  0.4036,  0.0082,  0.0956, -0.4157]], requires_grad=True),
 Parameter containing:
 tensor([[-0.1304,  0.0814, -0.1622]], requires_grad=True))