<a href="https://colab.research.google.com/github/Faizaa01/Deep_Learning_Practices/blob/main/Pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)


2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Device name {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is available
Device name Tesla T4


Creating Tensors

In [6]:
a = torch.empty(2, 3)
a

tensor([[1.4509e-21, 0.0000e+00, 6.1863e-23],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

In [9]:
# torch.zeros(2,3)
# torch.ones(2,3)
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [10]:
torch.manual_seed(100) #fixed value
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [21]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [22]:
torch.linspace(1,10,8)

tensor([ 1.0000,  2.2857,  3.5714,  4.8571,  6.1429,  7.4286,  8.7143, 10.0000])

In [40]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)
x.shape

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Size([2, 3])

In [34]:
torch.empty_like(x)
# torch.zeros_like(x)
# torch.ones_like(x)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [38]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [44]:
x.dtype

torch.int64

In [42]:
torch.tensor([[1.0,2.0,3.0]], dtype=torch.int32)
torch.tensor([[1,2,3]], dtype=torch.float32)

tensor([[1., 2., 3.]])

In [47]:
#to transfer dtype
x = x.to(torch.float32)
x.dtype

torch.float32

In [53]:
print(x+2,"\n",
      x-2,"\n",
      x*2,"\n",
      x/2,"\n",
      x//3,"\n",
      x**2,"\n",
      x%2,
)

tensor([[3., 4., 5.],
        [6., 7., 8.]]) 
 tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]]) 
 tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]]) 
 tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]]) 
 tensor([[0., 0., 1.],
        [1., 1., 2.]]) 
 tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]]) 
 tensor([[1., 0., 1.],
        [0., 1., 0.]])


In [56]:
c = torch.tensor([-1.1,-2.2,-3.3,-4.4])
torch.abs(c)
# torch.neg(c)
# torch.round(c)
# torch.ceil(c)

tensor([1.1000, 2.2000, 3.3000, 4.4000])

In [60]:
c = torch.tensor([100,200,300])
torch.clamp(c, min=1, max=2)

tensor([2, 2, 2])

In [61]:
e = torch.randint(size=(3,2), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 3.],
        [8., 7.],
        [4., 6.]])

In [73]:
print(torch.sum(e),
      torch.sum(e, dim=0),
      torch.sum(e, dim=1),
      torch.prod(e))

tensor(32.) tensor([16., 16.]) tensor([ 7., 15., 10.])


In [74]:
print(torch.mean(e),
torch.mean(e, dim=1),
torch.mean(e, dim=0),
torch.median(e),
torch.std(e),
torch.var(e),
)

tensor(5.3333) tensor([3.5000, 7.5000, 5.0000]) tensor([5.3333, 5.3333]) tensor(4.) tensor(16128.)


In [76]:
print(torch.max(e),
  torch.min(e),
  torch.argmin(e), #index of min value
  torch.argmax(e), #index of max value
)

tensor(8.) tensor(3.) tensor(1) tensor(2)


In [78]:
b = torch.randint(size=(3,2), low=0, high=10)
d = torch.randint(size=(2,2), low=0, high=10)
b, d

(tensor([[3, 9],
         [4, 0],
         [5, 7]]),
 tensor([[5, 9],
         [9, 7]]))

In [79]:
torch.matmul(b,d)

tensor([[96, 90],
        [20, 36],
        [88, 94]])

In [80]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
torch.dot(vector1, vector2)

tensor(11)

In [82]:
torch.transpose(b, 0, 1)

tensor([[3, 4, 5],
        [9, 0, 7]])

In [84]:
f = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
torch.det(f)

tensor(-110.)

In [85]:
torch.inverse(f)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

In [86]:
g = torch.randint(size=(2,2), low=0, high=10)
h = torch.randint(size=(2,2), low=0, high=10)
g, h

(tensor([[7, 8],
         [3, 6]]),
 tensor([[1, 5],
         [5, 0]]))

In [90]:
g>h, g<h, g==h, g!=h

(tensor([[ True,  True],
         [False,  True]]),
 tensor([[False, False],
         [ True, False]]),
 tensor([[False, False],
         [False, False]]),
 tensor([[True, True],
         [True, True]]))

In [93]:
k = torch.tensor([10,20,30])
k, torch.log(k), torch.exp(k), torch.sqrt(k)

(tensor([10, 20, 30]),
 tensor([2.3026, 2.9957, 3.4012]),
 tensor([2.2026e+04, 4.8517e+08, 1.0686e+13]),
 tensor([3.1623, 4.4721, 5.4772]))

In [103]:
l = torch.tensor([0.0001,0.005,.09])
torch.sigmoid(l)

tensor([0.5000, 0.5012, 0.5225])

In [104]:
torch.softmax(l, dim=0), torch.relu(l)

(tensor([0.3227, 0.3243, 0.3530]),
 tensor([1.0000e-04, 5.0000e-03, 9.0000e-02]))

In [105]:
i = torch.rand(2,3)
j = torch.rand(2,3)
i, j

(tensor([[0.9233, 0.9178, 0.7590],
         [0.7775, 0.6179, 0.3379]]),
 tensor([[0.2170, 0.9454, 0.7116],
         [0.1157, 0.6574, 0.3451]]))

In [106]:
i.add_(j) #inplace add operation

tensor([[1.1403, 1.8632, 1.4706],
        [0.8933, 1.2752, 0.6830]])

In [108]:
torch.relu_(j)
# j.relu_()

tensor([[0.2170, 0.9454, 0.7116],
        [0.1157, 0.6574, 0.3451]])

In [111]:
a = torch.tensor([1,2,3,4])
b = a
b[2] = 30
a, b

(tensor([ 1,  2, 30,  4]), tensor([ 1,  2, 30,  4]))

In [113]:
b = a.clone()
id(a), id(b)

(132925515592832, 132925515619280)